module Contexts
  module SurveyContexts
    def create_surveys
      @daily1 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 8.0, quality_of_sleep: 3, academic_stress: 4, life_stress: 5, soreness: 3, ounces_of_water_consumed: 18.0, hydration_quality: true, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily2 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 10.0, quality_of_sleep: 2, academic_stress: 3, life_stress: 5, soreness: 5, ounces_of_water_consumed: 13.0, hydration_quality: false, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily3 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 9.0, quality_of_sleep: 3, academic_stress: 5, life_stress: 5, soreness: 1, ounces_of_water_consumed: 20.0, hydration_quality: true, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily4 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 4.0, quality_of_sleep: 1, academic_stress: 4, life_stress: 5, soreness: 3, ounces_of_water_consumed: 18.0, hydration_quality: true, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily5 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 8.0, quality_of_sleep: 3, academic_stress: 4, life_stress: 5, soreness: 3, ounces_of_water_consumed: 15.0, hydration_quality: false, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily6 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 5.0, quality_of_sleep: 5, academic_stress: 5, life_stress: 3, soreness: 4, ounces_of_water_consumed: 17.0, hydration_quality: true, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily7 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 7.0, quality_of_sleep: 4, academic_stress: 1, life_stress: 1, soreness: 1, ounces_of_water_consumed: 21.0, hydration_quality: true, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)
      @daily8 = Survey.create(user_id: 1, survey_type: "Daily Wellness", season: "fall", session_load: nil, daily_load: nil, daily_strain: nil, monotony: nil, hours_of_sleep: 6.0, quality_of_sleep: 5, academic_stress: 5, life_stress: 5, soreness: 5, ounces_of_water_consumed: 14.0, hydration_quality: false, player_rpe_rating: nil, player_personal_performance: nil, participated_in_full_practice: nil, minutes_participated: nil, expected_session_load: nil, practice_id: nil)

      @post1 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 7.0, daily_load: 7.0, daily_strain: 3.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 5, player_personal_performance: 7, participated_in_full_practice: true, minutes_participated: 100, expected_session_load: 6.0, practice_id: 1, weekly_strain: 21.0, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post2 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 5.0, daily_load: 5.0, daily_strain: 4.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 6, player_personal_performance: 5, participated_in_full_practice: true, minutes_participated: 105, expected_session_load: 6.7, practice_id: 2, weekly_strain: 31.0, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post3 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 8.0, daily_load: 8.0, daily_strain: 5.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 3, player_personal_performance: 9, participated_in_full_practice: true, minutes_participated: 120, expected_session_load: 8.5, practice_id: 3, weekly_strain: 26.0, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post4 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 7.5, daily_load: 7.5, daily_strain: 3.7, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 4, player_personal_performance: 7, participated_in_full_practice: false, minutes_participated: 90, expected_session_load: 4.6, practice_id: 4, weekly_strain: 22.4, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post5 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 7.4, daily_load: 7.4, daily_strain: 3.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 5, player_personal_performance: 2, participated_in_full_practice: true, minutes_participated: 100, expected_session_load: 6.2, practice_id: 5, weekly_strain: 25.0, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post6 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 5.4, daily_load: 5.4, daily_strain: 8.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 6, player_personal_performance: 7, participated_in_full_practice: true, minutes_participated: 140, expected_session_load: 6.0, practice_id: 6, weekly_strain: 21.0, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post7 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 7.0, daily_load: 7.0, daily_strain: 3.0, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 5, player_personal_performance: 7, participated_in_full_practice: true, minutes_participated: 100, expected_session_load: 6.0, practice_id: 7, weekly_strain: 25.6, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
      @post8 = Survey.create(user_id: 1, survey_type: "Post-Practice", season: "fall", session_load: 8.0, daily_load: 8.0, daily_strain: 4.5, hours_of_sleep: nil, quality_of_sleep: nil, academic_stress: nil, life_stress: nil, soreness: nil, ounces_of_water_consumed: nil, hydration_quality: nil, player_rpe_rating: 7, player_personal_performance: 5, participated_in_full_practice: true, minutes_participated: 80, expected_session_load: 4.8, practice_id: 8, weekly_strain: 20.7, weekly_load: 40, acute_load: 50.0, chronic_load: 200.0, a_c_ratio: 4.0)
    end

    def delete_surveys
      @daily1.delete
      @daily2.delete
      @daily3.delete
      @daily4.delete
      @daily5.delete
      @daily6.delete
      @daily7.delete
      @daily8.delete

      @post1.delete
      @post2.delete
      @post3.delete
      @post4.delete
      @post5.delete
      @post6.delete
      @post7.delete
      @post8.delete
    end
  end
end 
